# Generated by Django 3.2 on 2021-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210424_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='types',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
