# Generated by Django 3.2 on 2021-04-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210426_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock'),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, default='SOME STRING', max_length=100),
        ),
    ]
