# Generated by Django 3.2 on 2021-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_item_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, default='SOME STRING', max_length=100),
        ),
    ]
