# Generated by Django 3.2 on 2021-04-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_item_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='types_link',
        ),
        migrations.RemoveField(
            model_name='item',
            name='types',
        ),
    ]
