# Generated by Django 3.2 on 2021-04-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210426_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='types_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
