# Generated by Django 3.2 on 2021-04-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_item_image'),
    ]

    operations = [
    ]
