# Generated by Django 3.2 on 2021-04-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_transfer_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='types_link',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock'),
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='SAME STRING', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, default='SAME STRING'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
