# Generated by Django 3.2.5 on 2021-07-20 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20210720_1557'),
        ('checkout', '0003_auto_20210515_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='my_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='myaccount.myaccount'),
        ),
    ]
