# Generated by Django 3.2.5 on 2021-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_alter_myaccount_default_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='default_address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='default_city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
